import Head from "next/head";
import Image from "next/image";
import Auth from "./auth";
import Rewards from "./rewards";

export default function Home() {
  const auth = true;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {auth ? <Rewards /> : <Auth />}
    </div>
  );
}
